# Generated by Django 5.1.1 on 2024-10-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupinvitation_groupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
